#!/bin/bash


FILE=~/.htb/config

if [ -f "$FILE" ]; then
    echo "htb à déjà été configuerer"

if [ "$1" == "-init" ]; then
        sudo openvpn ~/vpn/lab_0x307845.ovpn && echo "Vous n'êtes plus connecté aux machines !"
        exit 0
if [ "$1" == "-m" ]; then
        sudo openvpn ~/vpn/lab_0x307845.ovpn && echo "Vous n'êtes plus connecté aux machines !"
        exit 0
elif [ "$1" == "-s" ]; then
        sudo openvpn ~/vpn/starting_point_0x307845.ovpn && echo "Vous n'êtes plus bien connecté aux starting point !"
        exit 0
elif [ "$1" == "-e" ]; then
        sudo openvpn ~/vpn/endgames_0x307845.ovpn && echo "Vous n'êtes plus bien connecté aux endgames !"
        exit 0
elif [ "$1" == "-f" ]; then
        sudo openvpn ~/vpn/fortresses_0x307845.ovpn && echo "Vous n'êtes plus bien connecté aux forteresse !"
        exit 0
elif [ "$1" == "-h" ]; then
        echo "-m : Connexion vers les machines"
        echo "-s : Connexion vers les starting points"
        echo "-e : Connexion vers les machines endgames"
        echo "-f : Connexion vers les machines forteresses"
        exit 0
else
        echo "Arguement invalide !"
fi

