#!/bin/bash
PUBLIC_IP=`wget http://ipecho.net/plain -O - -q ; echo`
PRIVATE_IP=`ifconfig wlan0 | grep inet | grep -v inet6 | awk '{print $2}'; echo`
echo "=========================="
echo "Public ip : ${PUBLIC_IP}"
echo "Private ip : ${PRIVATE_IP}"
echo "=========================="
